Feat/product shelf fixed
deco-sites/otica-isabela pull request #41
Opened 2023-09-05 03:47 UTC by aka-sacci

## What is this contribution about?

Fix: Several changes in productShelf loader logic; Search by many product id filter added

## How to test it?

https://deco.cx/admin/sites/king-of-lenses/blocks/category3?sidebarMode=edit&tab=0 - Change it and compare the results

2023-09-05 19:59 UTC, gustavo-vasconcellos requested changes

2023-09-05 19:59 UTC, gustavo-vasconcellos commented on packs/types.ts
> +  ordenacao: "none" | "nome";
```suggestion
  ordenacao: "none" | "mais-vendidos" | "ofertas" | "menor-preco"
```

2023-09-05 19:59 UTC, gustavo-vasconcellos commented on packs/types.ts
> +  id?: Array<string>;
```suggestion
  id?: string[];
```

2023-09-05 19:59 UTC, gustavo-vasconcellos commented on packs/utils/transform.ts
> +        }`,
Os produtos podem ter ate 3 cores, entao falta tratar o `variant.Color3`. Acho que vale a pena criar uma funçao para receber as cores e retornar o objeto pronto do addtionalProperty

2023-09-05 19:59 UTC, gustavo-vasconcellos commented on packs/utils/paths.ts
> +  };
Se eu entendi o que essa `stringifyParams` faz, seria algo que pode trocar por isso abaixo?
![image](https://github.com/deco-sites/otica-isabela/assets/29849615/bb95815e-7726-4697-bfe8-e015d13bcd78)

2023-09-06 01:41 UTC, aka-sacci commented on packs/types.ts
> +  ordenacao: "none" | "nome";
corrigido

2023-09-06 01:41 UTC, aka-sacci commented on packs/types.ts
> +  id?: Array<string>;
corrigido

2023-09-06 01:42 UTC, aka-sacci commented on packs/utils/paths.ts
> +  };
realmente, era desnecessário. Removi o stringfyParams e refatorei tudo que foi necessário

2023-09-06 01:45 UTC, aka-sacci commented on packs/utils/transform.ts
> +        }`,
automatizei esse unitCode. Ficou tipo
color1
color1 / color2
color1 / color2 / color3
em casos que houver/não houver tais dados

2023-09-07 20:32 UTC, aka-sacci commented
Merged, conforme solicitado!

2023-09-07 20:32 UTC, merged