feat(packs): add product to card added
deco-sites/otica-isabela pull request #62
Opened 2023-10-13 03:33 UTC by aka-sacci

## What is this contribution about?

Add item to cart

2023-10-13 18:21 UTC, gustavo-adaptio requested changes

2023-10-13 18:21 UTC, gustavo-adaptio commented on routes/live/invoke/_middleware.tsx
> +    )?.SessionKey;
```suggestion
  if (cookies[ISABELA_DIAS_CLIENT_COOKIE]) return res;

  const sessionToken =
    await ctx.state.invoke(
        "deco-sites/otica-isabela/loaders/store/session.ts"
      )?.SessionKey;
```

2023-10-13 18:21 UTC, gustavo-adaptio commented on routes/live/invoke/_middleware.tsx
> +    )?.SessionKey;
Voce ja esta verificando se tem o cookie na linha 39, voce nao precisa verificar de novo pois se chegar na linha 41 significa que nao tem.

2023-10-13 18:21 UTC, gustavo-adaptio commented on routes/live/invoke/_middleware.tsx
>    );
Ao mesmo tempo se nao tem voce ja fez a chamada da Session em cima e ja tem os dados dela, logo voce nao precisa chamar de novo aqui. 
Se nao tiver o cookie, basta chamar a API **uma vez** obter os dados e salva-los no Cookie.

2023-10-13 19:58 UTC, aka-sacci commented on routes/live/invoke/_middleware.tsx
> +    )?.SessionKey;
ISABELA_DIAS_CLIENT_COOKIE e ISABELA_DIAS_SESSION_COOKIE. São cookies diferentes: Um armazena o SessionKey e o outro o IdSessionCustomer
Cara, na real, vamos falar disso no daily de hoje, por que o endpoint de inicio sessao funciona de uma forma meio curiosa

2023-10-15 00:53 UTC, gustavo-vasconcellos approved these changes

2023-10-15 00:53 UTC, gustavo-vasconcellos approved these changes

2023-10-15 01:09 UTC, merged